{% set version = "0.4.2" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gtextras
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gtExtras_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gtExtras/gtExtras_{{ version }}.tar.gz
  sha256: 2e187896617b4ced433b70ab8d7b090dccdc334a2aa844ab98eacd15a51cc96f

build:
  merge_build_host: true  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-commonmark
    - r-dplyr >=1.0.8
    - r-fontawesome >=0.2.2
    - r-ggplot2 >=3.3.5
    - r-glue >=1.6.1
    - r-gt >=0.5
    - r-htmltools >=0.5.2
    - r-paletteer >=1.4.0
    - r-rlang >=1.0.1
    - r-scales >=1.2.0
  run:
    - r-base
    - r-commonmark
    - r-dplyr >=1.0.8
    - r-fontawesome >=0.2.2
    - r-ggplot2 >=3.3.5
    - r-glue >=1.6.1
    - r-gt >=0.5
    - r-htmltools >=0.5.2
    - r-paletteer >=1.4.0
    - r-rlang >=1.0.1
    - r-scales >=1.2.0

test:
  commands:
    - $R -e "library('gtExtras')"           # [not win]
    - "\"%R%\" -e \"library('gtExtras')\""  # [win]

about:
  home: https://github.com/jthomasmock/gtExtras, https://jthomasmock.github.io/gtExtras/
  license: MIT
  summary: Provides additional functions for creating beautiful tables with 'gt'. The functions are generally wrappers around boilerplate or adding capabilities that are currently not built into 'gt'.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
